---
title: "Multivariante"
author: "Pedro Biel"
date: "16/2/2021"
output: html_document
---


# Datos multidimensionales

## Ejemplo con tres dimensiones

```{r}
ans = sample(c('Sí', 'No'), size = 100, replace = T)
sex = sample(c('H', 'M'), size = 100, replace = T)
place = sample(c('San Francisco', 'Barcelona', 'Valencia', 'Cobija', 'Asturias'), size = 100, replace = T)

table(sex, ans, place)

ftable(sex, ans, place)
ftable(sex, ans, place, col.vars = c('sex', 'ans'))
```

### Filtrar las tablas

```{r}
table(sex, ans, place)['M', 'Sí', 'San Francisco']
table(sex, ans, place)[, 'Sí', 'Valencia']
table(sex, ans, place)[, 'No', ]
table(sex, ans, place)['M', , 'Cobija']
```

### Frecuencias relativas

```{r}
prop.table(table(sex, ans, place))  # Frecuencias relativas globales
prop.table(table(sex, ans, place), margin = 3)  # Frecuencia marginal por lugar
prop.table(table(sex, ans, place), margin = c(1,3))  # Frecuencia relativa marginal por sexo y lugar

ftable(prop.table(table(sex, ans, place)))
```

