---
title: "Ejercicio Calcular estadísticas de datos agrupados"
author: "Pedro Biel"
date: "10/3/2021"
output: html_document
---


# Calcular estadísticos de datos agrupados

```{r}
crabs = read.table('datacrab.txt', header = TRUE)
str(crabs)
cw = crabs$width
cw
```

```{r}
TablaFrecs.L = function(x,L,V){
  x_cut = cut(x, breaks=L, right=FALSE, include.lowest=V)
  intervals = levels(x_cut)
  mc = (L[1:(length(L)-1)]+L[2:length(L)])/2
  Fr.abs = as.vector(table(x_cut)) 
  Fr.rel = round(Fr.abs/length(x),4)
  Fr.cum.abs = cumsum(Fr.abs)
  Fr.cum.rel = cumsum(Fr.rel)
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel)
  tabla
}

vector = c(20.95, 22.25, 23.55, 24.85, 26.15, 27.45, 28.75, 30.05, 31.35, 32.65, 33.95)
tabla = TablaFrecs.L(cw, L = vector, V = FALSE)
tabla
```

```{r}
A = diff(range(cw) / nclass.scott(cw))
A = ceiling(A * 10)
A = A / 10
A
```

```{r}
L1 = min(cw) - (1/2 * 0.1)  # El mínimo menos la mitad de la precisión
L1
```

```{r}
L = L1 + A * (0:10)
L
```

Ahora ya podemos calcular los estadísticos:

```{r}
TOT = tabla$Fr.cum.abs[10]
TOT
```

## Media:

```{r}
anchura.media = round(sum(tabla$Fr.abs * tabla$mc) / TOT, 3)
anchura.media
```

## Varianza:

```{r}
anchura.var = round(sum(tabla$Fr.abs * tabla$mc^2) / TOT - anchura.media^2, 3)
anchura.media
```

## Desviación típica:

```{r}
anchura.dt = round(sqrt(anchura.var), 3)
anchura.dt
```

## Intervalo modal:

```{r}
I.modal = tabla$intervals[which(tabla$Fr.abs == max(tabla$Fr.abs))]
I.modal
```

## Intervalo crítico

```{r}
I.critico = tabla$intervals[which(tabla$Fr.cum.rel >= 0.5)]
I.critico[1]
```

## Aproximación de la mediana de los datos "reales".

```{r}
n = TOT
Lc = L[4]
Lc.pos = L[5]
Ac = L[5] - L[4]
Nc.ant = tabla$Fr.cum.abs[3]
nc = tabla$Fr.abs[4]
M = Lc + Ac * ((n/2) - Nc.ant) / nc
M
```

### Mediana de los datos reales

```{r}
median(cw)
```

## Primer cuantil

```{r}
aprox.quantile.p = function(Lcrit, Acrit, n, p, Ncrit.ant, ncrit){
  round(Lcrit + Acrit * (p * n - Ncrit.ant) / ncrit, 3)
}
aprox.quantile.p(Lc, Ac, n, 0.25, Nc.ant, nc)
```

```{r}
aprox.quantile.p(Lc, Ac, n, 0.75, Nc.ant, nc)
```

### Cuantiles "reales"

```{r}
quantile(cw, 0.25)
```

```{r}
quantile(cw, 0.75)
```




















