---
title: "La función cut de R"
author: "Pedro Biel"
date: "8/3/2021"
output: html_document
---

# La función `cut`

```{r}
petals = iris$Petal.Length
cut(petals, breaks = 5, right = FALSE)
k = ceiling(sqrt(length(petals)))
cut(petals, breaks = k, right = FALSE)
cut(petals, breaks = c(1, 2, 3, 4, 5, 6, 7), right = FALSE)
cut(petals, breaks = 5, right = FALSE, labels = FALSE)
cut(petals, breaks = 5, right = FALSE, labels = c('XPeq', 'Peq', 'Norm', 'Grand', 'XGrand'))
```

```{r}
irisdf = iris
petals = iris$Petal.Length
irisdf$div1 = cut(petals, breaks = 5, right = FALSE)
k = ceiling(sqrt(length(petals)))
irisdf$div2 = cut(petals, breaks = k, right = FALSE)
irisdf$div3 = cut(petals, breaks = c(1, 2, 3, 4, 5, 6, 7), right = FALSE)
irisdf$div4 = cut(petals, breaks = 5, right = FALSE, labels = FALSE)
irisdf$div5 = cut(petals, breaks = 5, right = FALSE, labels = c('XPeq', 'Peq', 'Norm', 'Grand', 'XGrand'))
irisdf
```

```{r}
TablaFrecs = function(x,k,A,p){ 
  L = min(x)-p/2+A*(0:k)
  x_cut = cut(x, breaks = L, right=FALSE)
  intervals = levels(x_cut)
  mc = (L[1]+L[2])/2+A*(0:(k-1))
  Fr.abs = as.vector(table(x_cut)) 
  Fr.rel = round(Fr.abs/length(x),4) 
  Fr.cum.abs = cumsum(Fr.abs) 
  Fr.cum.rel = cumsum(Fr.rel)
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel)
  tabla
}

# Funciones para las tablas de frecuencias

TablaFrecs.L = function(x,L,V){
  x_cut = cut(x, breaks=L, right=FALSE, include.lowest=V)
  intervals = levels(x_cut)
  mc = (L[1:(length(L)-1)]+L[2:length(L)])/2
  Fr.abs = as.vector(table(x_cut)) 
  Fr.rel = round(Fr.abs/length(x),4)
  Fr.cum.abs = cumsum(Fr.abs)
  Fr.cum.rel = cumsum(Fr.rel)
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel)
  tabla
  }
```

La tabla de frecuencias de la longitud de los pétalos de *Iris* es:
(k debería obtenerse por alguna regla descrita)

```{r}
TablaFrecs(petals, k = 6, A = 1, p = 0.1)
TablaFrecs.L(petals, L = 1:7, V = FALSE)
TablaFrecs.L(petals, L = c(1, 3, 4, 5, 5.5, 6, 6.5, 7), V = FALSE)
```



