---
title: "R y Python"
author: "Pedro Biel"
date: "21/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reticulate

```{r}
library(reticulate)
# Para usar la versi칩n de python de Anaconda
use_python("C:/Users/pjbie/anaconda3_2020_11/python")
# Al instalar un nuevo paquete, si se le ha dicho que use el python de Anaconda, adem치s lo instalar치 en Anaconda.
#py_install("nombre_del_paquete_a_instalar")

os = import("os")
os$listdir(".")
```

```{r}
source_python("suma.py")
suma(3, 4)
```

```{r}
np = import("numpy", convert = FALSE)
# convert = FALSE -> no se va a hacer una conversi칩n de objetos python a objetos R.

x = np$array(c(1:4))
sum = x$cumsum()
print(sum)

py_to_r(sum)
```

## Ayuda

```{r}
#help(py_to_r)
py_help(os$chdir)
```

## Arrays
```{r}
a = np_array(c(1:10), dtype="float16")
a

# Estilo de guardado en memoria de C.
b = np_array(c(1:10), order="C")
b
```

## Python

```{r}
datos = iris
head(datos)
datos_py = r_to_py(datos)
```

```{python}
import numpy as np
import pandas as pd

r.datos_py.head()
```

```{r}
library(Matrix)
N = 6
set.seed(123)
sparse_mat = sparseMatrix(
  i = sample(N, N, replace = F),
  j = sample(N, N, replace = F),
  x = runif(N),
  dims = c(N,N)
)
sparse_mat
sparse_mat_py = r_to_py(sparse_mat)
```

```{python}
r.sparse_mat_py
# Puedo hacer modificaciones de sparse_mat_py en python.
```

```{r}
# Recuperar sparse_mat_py en R.
py_to_r(sparse_mat_py)
```


